
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_listen_port: 9096
  grpc_server_max_concurrent_streams: 1000

common:
  instance_addr: 127.0.0.1
  replication_factor: 1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
  - from: 2025-01-01
    index:
      period: 24h
      prefix: index_
    store: tsdb
    object_store: filesystem
    schema: v13

frontend:
  encoding: protobuf

pattern_ingester:
  enabled: true

limits_config:
  allow_structured_metadata: true

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100